ALTER TABLE org_unit ADD COLUMN is_review_data BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE production_line ADD COLUMN is_review_data BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE equipment ADD COLUMN is_review_data BOOLEAN NOT NULL DEFAULT FALSE;
