import { setTarget } from '../../utils/navigation'
import { chinaTime } from '../../utils/display'
import { request } from '../../utils/request'
import { collectSubscriptionCredit, refreshSubscriptionHarvesting } from '../../utils/subscription'
interface Item { id:string; type:string; title:string; content:string; sourceType?:string; sourceId?:string; requiresAcknowledgement:boolean; readAt?:string; acknowledgedAt?:string; createdAt:string }
Page({sequence:0,data:{items:[] as Item[],filter:'all',hasMore:false,total:0,unread:0,awaiting:0,loading:false,error:''},onShow(){refreshSubscriptionHarvesting();this.load()},onPullDownRefresh(){this.load().finally(()=>wx.stopPullDownRefresh())},async load(append=false){const sequence=++this.sequence;this.setData({loading:true,error:''});try{const inbox=await request<{unread:number;awaitingAcknowledgement:number;items:Item[];total:number;hasMore:boolean}>('/notifications?limit=50&offset='+(append?this.data.items.length:0)+'&unreadOnly='+(this.data.filter==='unread'));if(sequence!==this.sequence)return;const rows=inbox.items.map(item=>({...item,createdAt:chinaTime(item.createdAt)}));this.setData({items:append?[...this.data.items,...rows.filter(r=>!this.data.items.some(i=>i.id===r.id))]:rows,unread:inbox.unread,awaiting:inbox.awaitingAcknowledgement,total:inbox.total,hasMore:inbox.hasMore})}catch(reason){if(sequence===this.sequence)this.setData({error:reason instanceof Error?reason.message:'消息加载失败'})}finally{if(sequence===this.sequence)this.setData({loading:false})}},
  more(){if(!this.data.loading&&this.data.hasMore)this.load(true)},changeFilter(e:any){this.setData({filter:e.currentTarget.dataset.filter,items:[],hasMore:false});this.load()},
  async open(e:WechatMiniprogram.BaseEvent){const item=this.data.items[Number(e.currentTarget.dataset.index)];if(!item)return;try{await collectSubscriptionCredit();if(!item.readAt)await request(`/notifications/${item.id}/read`,'POST',{acknowledge:item.sourceType!=='SCHEDULE_ASSIGNMENT'&&item.requiresAcknowledgement});await this.load();if(item.sourceType==='EQUIPMENT_INCIDENT'&&item.sourceId)wx.navigateTo({url:`/pages/incident-detail/index?id=${item.sourceId}`});else if(item.sourceType==='PERFORMANCE_CASE'||item.sourceType==='SCHEDULE_ASSIGNMENT'){const kind=item.sourceType==='PERFORMANCE_CASE'?'score':'schedule';const date=await request<string>('/notifications/'+item.id+'/source-date');setTarget(kind,item.sourceId||'',date);wx.switchTab({url:'/pages/'+kind+'/index'})}}catch(reason){wx.showToast({title:reason instanceof Error?reason.message:'消息处理失败',icon:'none'})}}
})
