<script setup lang="ts">
import {computed,onMounted,onUnmounted,reactive,ref,watch} from 'vue'
import {apiGet,apiPost,apiUpload} from './api/client'
import SearchSelect from './SearchSelect.vue'
import type {FormSpec,Option} from './workflow'
const props=defineProps<{spec:FormSpec}>(),emit=defineEmits(['close','saved'])
const data=reactive<Record<string,any>>({...props.spec.initial}),busy=ref(false),error=ref(''),rules=ref<Option[]>([]),rulesBusy=ref(false),root=ref<HTMLElement|null>(null)
const baseline=JSON.stringify(props.spec.initial||{}),dirty=computed(()=>JSON.stringify(data)!==baseline||files.value.length>0),notice=ref('')
function close(){if(busy.value)return;if(dirty.value&&!confirm('尚有未提交内容，确认放弃并关闭？如需保留，请取消后点击保存草稿。'))return;emit('close')}
function save(){if(!props.spec.draftKey)return;try{sessionStorage.setItem(props.spec.draftKey,JSON.stringify(data));notice.value='文字草稿已保存，附件重新打开后需重新选择'}catch{error.value='草稿保存失败，请保留当前页面'}}
function beforeUnload(e:BeforeUnloadEvent){if(dirty.value){e.preventDefault();e.returnValue=''}}
const files=ref<File[]>([]),uploaded=new Map<File,string>();let ruleSequence=0
watch(()=>data.occurredAt,()=>loadRules())
async function loadRules(){if(!props.spec.ruleType)return;const seq=++ruleSequence,previousRule=data.ruleCode;rulesBusy.value=true;try{const date=String(data.occurredAt||props.spec.ruleDate||'').slice(0,10);const rows=await apiGet<any[]>('/score-rules?type='+props.spec.ruleType+'&date='+encodeURIComponent(date));if(seq===ruleSequence){rules.value=rows.map(rule=>({value:rule.code,label:rule.code+' · '+rule.title}));if(previousRule&&!rules.value.some(rule=>rule.value===previousRule)){data.ruleCode='';notice.value='原选规则在当前日期已失效，请重新选择'}}}catch(e){if(seq===ruleSequence){rules.value=[];data.ruleCode='';error.value=e instanceof Error?e.message:'规则加载失败'}}finally{if(seq===ruleSequence)rulesBusy.value=false}}
function selectFiles(event:Event){const selected=Array.from((event.target as HTMLInputElement).files||[]);if(selected.length>(props.spec.singleFile?1:9)){error.value='附件数量超出限制';return}files.value=selected;error.value=''}
async function submit(){if(busy.value||rulesBusy.value)return;busy.value=true;error.value='';try{
 const payload={...data};for(const f of props.spec.fields){if(f.required&&(payload[f.key]==null||String(payload[f.key]).trim()===''))throw new Error('请填写'+f.label)}
 for(const f of props.spec.fields){if(f.type==='datetime-local'&&payload[f.key])payload[f.key]=payload[f.key]+(payload[f.key].length===16?':00':'')+'+08:00';if(f.type==='number'&&payload[f.key]!==''&&payload[f.key]!=null)payload[f.key]=Number(payload[f.key]);if(!f.required&&payload[f.key]==='')payload[f.key]=null}
 if(props.spec.fileKey){const ids=[...(props.spec.singleFile?[]:(props.spec.initial?.[props.spec.fileKey]||[]))];for(const file of files.value){let id=uploaded.get(file);if(!id){id=(await apiUpload<{id:string}>('/attachments',file)).id;uploaded.set(file,id)}ids.push(id)}payload[props.spec.fileKey]=props.spec.singleFile?(ids[0]||props.spec.initial?.[props.spec.fileKey]||null):ids}
 const result=await apiPost(props.spec.path,payload,props.spec.method||'POST');if(props.spec.draftKey)sessionStorage.removeItem(props.spec.draftKey);emit('saved',result)
 }catch(e){error.value=e instanceof Error?e.message:'保存失败，请重试'}finally{busy.value=false}}
let previous:HTMLElement|null=null
function keys(e:KeyboardEvent){if(e.key==='Escape'&&!busy.value)close();if(e.key==='Tab'){const nodes=Array.from(root.value?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')||[]);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===root.value)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}
onMounted(()=>{if(props.spec.draftKey){try{const draft=sessionStorage.getItem(props.spec.draftKey);if(draft){Object.assign(data,JSON.parse(draft));notice.value='已恢复文字草稿，请核对后提交'}}catch{}}window.addEventListener('beforeunload',beforeUnload);previous=document.activeElement as HTMLElement;root.value?.focus();loadRules();document.addEventListener('keydown',keys)})
onUnmounted(()=>{window.removeEventListener('beforeunload',beforeUnload);document.removeEventListener('keydown',keys);previous?.focus()})
</script>
<template><div class="workflow-overlay"><section ref="root" class="workflow-dialog" role="dialog" aria-modal="true" aria-labelledby="business-title" tabindex="-1"><div class="panel-head"><h2 id="business-title">{{spec.title}}</h2><button type="button" class="secondary" :disabled="busy" @click="close">关闭</button></div><p v-if="spec.description">{{spec.description}}</p><form @submit.prevent="submit"><fieldset :disabled="busy"><label v-for="f in spec.fields" :key="f.key">{{f.label}}<small v-if="f.required"> *</small><textarea v-if="f.type==='textarea'" v-model="data[f.key]" :required="f.required" :maxlength="f.max||2000" rows="4"/><SearchSelect v-else-if="f.type==='select'&&(f.multiple||f.key==='ownerId')" v-model="data[f.key]" :options="f.options||[]" :label="f.label" :multiple="f.multiple" :disabled="busy"/><select v-else-if="f.type==='select'" v-model="data[f.key]" :required="f.required" :multiple="f.multiple"><option v-if="!f.multiple" value="">请选择</option><option v-for="o in f.key==='ruleCode'&&spec.ruleType?rules:f.options" :key="o.value" :value="o.value">{{o.label}}</option></select><input v-else-if="f.type==='files'" type="file" accept="image/*" :multiple="!spec.singleFile" :required="f.required&&!spec.initial?.[spec.fileKey||'']" @change="selectFiles"><input v-else-if="f.type==='checkbox'" v-model="data[f.key]" type="checkbox"><input v-else v-model="data[f.key]" :type="f.type||'text'" :required="f.required" :min="f.min" :max="f.max" :maxlength="f.max||2000" :step="f.type==='number'?1:undefined"></label></fieldset><p v-if="rulesBusy" class="caption">正在读取生效规则…</p><p v-if="error" class="error-box" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><button v-if="spec.draftKey" type="button" class="secondary" :disabled="busy" @click="save">保存文字草稿</button><button :disabled="busy||rulesBusy">{{busy?'正在保存…':'确认提交'}}</button></form></section></div></template>
<style>
.workflow-overlay{position:fixed;inset:0;background:#152c4680;z-index:1000;display:flex;justify-content:center;align-items:center;padding:24px;backdrop-filter:blur(3px)}.workflow-dialog{background:white;border-radius:20px;box-shadow:0 24px 80px #10203540;padding:28px;width:min(640px,100%);max-height:90vh;overflow:auto}.workflow-dialog fieldset{border:0;padding:0;margin:0}.workflow-dialog label{display:block;margin:16px 0;color:#40566b;font-size:14px}.workflow-dialog label input:not([type=checkbox]),.workflow-dialog textarea,.workflow-dialog select{display:block;width:100%;box-sizing:border-box;margin-top:7px;padding:10px;border:1px solid #d8e2ea;border-radius:8px;font:inherit}.workflow-dialog p{line-height:1.7;color:#66788b}.workflow-dialog input[type=checkbox]{margin-left:12px}.workflow-toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:14px 0}.workflow-list{display:grid;gap:12px}.workflow-item{padding:18px;border:1px solid #e2eaf1;border-radius:12px;background:#fff}.workflow-item.selected{border-color:#408aaa;background:#f4fbff}.workflow-item p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}.workflow-item small{color:#708497}.workflow-banner{padding:16px 20px;background:#edf6fb;border-left:3px solid #33849d;border-radius:8px;color:#356078;line-height:1.8;margin:14px 0}.workflow-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.workflow-tabs button[aria-pressed=true]{background:#1c6680;color:#fff}.workflow-detail{border-top:1px solid #dbe5ed;margin-top:18px;padding-top:18px}.workflow-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.workflow-danger{color:#ab403f}.workflow-badge{font-size:12px;padding:4px 8px;border-radius:6px;background:#edf3f6;color:#416575}.workflow-detail dt{font-size:12px;color:#708497}.workflow-detail dd{margin:6px 0 16px;white-space:pre-wrap}.workflow-link{border:0;background:transparent;color:#16748f;text-align:left;cursor:pointer}.workflow-empty{padding:28px;text-align:center;color:#7a8d9c}
</style>
