export interface Option {value:string;label:string}
export interface Field {key:string;label:string;type?:'text'|'textarea'|'select'|'number'|'datetime-local'|'date'|'checkbox'|'files';required?:boolean;options?:Option[];min?:number;max?:number;multiple?:boolean}
export interface FormSpec {title:string;description?:string;path:string;method?:'POST'|'PUT';initial?:Record<string,any>;fields:Field[];ruleType?:string;ruleDate?:string;fileKey?:string;singleFile?:boolean;draftKey?:string}
export interface Actor {userId:string;roles:string[];administrator:boolean}
export const labels:Record<string,string>={INCIDENT_CREATED:'创建异常档案',STATEMENT_SUBMITTED:'提交责任人说明',STATEMENT_APPROVED:'说明审核通过',STATEMENT_RETURNED:'说明退回',METADATA_UPDATED:'更新异常摘要',INVESTIGATION_SUBMITTED:'提交调查结论',INVESTIGATION_CONFIRMED:'确认调查结论',RESPONSIBILITY_CONFIRMED:'确认责任认定',CORRECTIVE_ACTION_CREATED:'建立整改措施',CORRECTIVE_ACTION_COMPLETED:'提交整改完成',CORRECTIVE_ACTION_ACCEPTED:'整改验收通过',CORRECTIVE_ACTION_RETURNED:'整改退回',DOSSIER_ARCHIVED:'档案归档',DOSSIER_REOPENED:'重新打开档案',APPROVE:'审核通过',RETURN:'退回修改',REJECT:'否决',DRAFT:'草稿',BASE:'基础分',PENALTY:'扣分',D_GRADE:'D级规则',ASSISTANT_ENGINEER:'助理工程师',SUPERVISOR:'主管',DEPARTMENT_MANAGER:'部长',PENDING:'待处理',SUBMITTED:'待审核',APPROVED:'已通过',OVERDUE:'已逾期',RETURNED:'已退回',REJECTED:'已否决',EFFECTIVE:'已生效',REVERSED:'已撤销',PENDING_ASSISTANT:'待助理审核',PENDING_SUPERVISOR:'待主管审核',WAITING_STATEMENTS:'待补充说明',UNDER_REVIEW:'说明审核中',INVESTIGATING:'调查中',RESPONSIBILITY_PENDING:'待认定责任',CORRECTING:'整改中',PENDING_ACCEPTANCE:'待验收',ARCHIVED:'已归档',VOID:'已作废',ACCEPTED:'已通过',CANCELLED:'已取消',CONFIRMED:'已确认',IN_PROGRESS:'处理中',PREVIEW:'待确认',PUBLISHED:'已发布',SUPERSEDED:'已被新版本替代',GENERAL:'一般',IMPORTANT:'重要',MAJOR:'重大',LOW:'低',MEDIUM:'中',HIGH:'高',BONUS:'加分',BASE_DEDUCTION:'基础扣分',SPECIAL_DEDUCTION:'特殊扣分',ADMONITION:'劝诫',SIMPLE:'简要调查',FIVE_WHY:'五问分析'}
export const label=(value:string)=>labels[value]||value||'—'
export const chinaTime=(value:string)=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—'
export const chinaInput=(date=new Date())=>new Date(date.getTime()+8*3600000).toISOString().slice(0,16)
export const textField=(key:string,name:string,required=true):Field=>({key,label:name,type:'textarea',required,max:2000})
export const choice=(key:string,name:string,values:string[]):Field=>({key,label:name,type:'select',required:true,options:values.map(value=>({value,label:label(value)}))})
export const peopleOptions=(people:any[])=>people.map(p=>({value:p.id,label:`${p.name} · ${p.employeeNo} · ${p.teamName||''}`}))
export const commentField=(required=false):Field=>({key:'comment',label:required?'处理意见（必填）':'处理意见',type:'textarea',required,max:1000})
