package com.acme.performance.settlement.service;

import com.acme.performance.admin.service.AuditLogService;
import com.acme.performance.auth.model.CurrentUser;
import com.acme.performance.common.api.ApiException;
import com.acme.performance.notification.service.NotificationService;
import com.acme.performance.organization.model.BusinessRoles;
import com.acme.performance.settlement.model.SettlementView;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.*;
import java.time.*;
import java.util.*;

@Service
public class SettlementService {
    private static final ZoneId ZONE=ZoneId.of("Asia/Shanghai");
    private static final Set<String> GRADES=Set.of("S","A","B1","B2","B3","C");
    private final SettlementAccess access;private final JdbcClient jdbc;private final AuditLogService audit;private final NotificationService notifications;private final GradeDistribution distribution=new GradeDistribution();
    public SettlementService(JdbcClient jdbc,AuditLogService audit,NotificationService notifications){this.jdbc=jdbc;this.access=new SettlementAccess(jdbc);this.audit=audit;this.notifications=notifications;}

    @Transactional
    public SettlementView preview(CurrentUser actor,String period,UUID orgId,String version,String requestId){
        requireSupervisor(actor);DGradeService.validatePeriod(period);UUID root=orgId==null?departmentId():orgId;requireDepartment(root);access.requireWrite(actor,root);
        if(version==null||!version.matches("[A-Za-z0-9._-]{1,32}"))invalid("INVALID_SETTLEMENT_VERSION","结算版本不合法");
        YearMonth month=YearMonth.parse(period);long pending=pendingCount(month,root);if(pending>0)throw new ApiException("PENDING_BUSINESS_EXISTS","本月仍有"+pending+"项绩效、申诉或异常业务未完成，封存已延后",HttpStatus.CONFLICT);
        UUID ruleVersionId=jdbc.sql("SELECT id FROM rule_version WHERE status IN ('PUBLISHED','RETIRED') AND effective_at<:end ORDER BY effective_at DESC LIMIT 1").param("end",month.plusMonths(1).atDay(1).atStartOfDay(ZONE).toOffsetDateTime()).query(UUID.class).optional().orElseThrow(()->new ApiException("RULE_VERSION_NOT_FOUND","结算周期无有效规则版本",HttpStatus.CONFLICT));
        List<ScoreData> scores=scores(period,root);if(scores.isEmpty())throw new ApiException("NO_ELIGIBLE_EMPLOYEES","本月没有有效排班的技术员或助理工程师",HttpStatus.CONFLICT);
        Map<UUID,ScoreData> byUser=new HashMap<>();scores.forEach(item->byUser.put(item.userId(),item));Set<UUID>dUsers=new HashSet<>(jdbc.sql("SELECT user_id FROM d_grade_nomination WHERE period=:period AND status='CONFIRMED'").param("period",period).query(UUID.class).list());
        List<GradeDistribution.ScoreInput> normal=scores.stream().filter(item->!dUsers.contains(item.userId())).map(this::rankInput).toList(),d=scores.stream().filter(item->dUsers.contains(item.userId())).map(this::rankInput).toList();List<GradeDistribution.Result> results=distribution.distribute(normal,d);
        UUID runId=UUID.randomUUID();try{jdbc.sql("INSERT INTO settlement_run(id,period,org_unit_id,settlement_version,rule_version_id,status,created_by) VALUES (:id,:period,:orgId,:version,:ruleVersionId,'PREVIEW',:actorId)").param("id",runId).param("period",period).param("orgId",root).param("version",version).param("ruleVersionId",ruleVersionId).param("actorId",actor.userId()).update();}catch(org.springframework.dao.DataIntegrityViolationException ex){throw new ApiException("SETTLEMENT_VERSION_EXISTS","该月结算版本已经存在",HttpStatus.CONFLICT);}
        access.snapshotRun(runId,root);
        for(var result:results){ScoreData item=byUser.get(result.userId());jdbc.sql("INSERT INTO settlement_candidate(run_id,user_id,total,base,bonus,penalty,proposed_grade,rank_no,manual_required,shift_count,average_score) VALUES (:runId,:userId,:total,:base,:bonus,:penalty,:grade,:rank,:manual,:shiftCount,:average)").param("runId",runId).param("userId",item.userId()).param("total",item.total()).param("base",item.base()).param("bonus",item.bonus()).param("penalty",item.penalty()).param("grade",result.proposedGrade()).param("rank",result.rank()).param("manual",result.manualRequired()).param("shiftCount",item.shiftCount()).param("average",item.average()).update();}
        audit.record(actor.userId(),"SETTLEMENT_PREVIEW","SETTLEMENT_RUN",runId,"{\"period\":\""+period+"\"}",requestId);notifySupervisors(runId,root,"月度绩效待确认",period+"月绩效已生成，请核对同分边界并完成确认。");return buildView(runId);
    }

    @Transactional(readOnly=true)public SettlementView view(CurrentUser actor,UUID runId){requireViewer(actor);access.require(actor,run(runId).orgId());return buildView(runId);}
    @Transactional(readOnly=true)public List<SettlementView> list(CurrentUser actor,String period){requireViewer(actor);DGradeService.validatePeriod(period);return jdbc.sql("SELECT id FROM settlement_run WHERE period=:period ORDER BY created_at DESC").param("period",period).query(UUID.class).list().stream().filter(id->access.canAccess(actor,run(id).orgId())).map(this::buildView).toList();}

    @Transactional
    public SettlementView voteBoundary(CurrentUser actor,UUID runId,UUID userId,String grade,String reason,String requestId){requireSupervisor(actor);RunRow run=lockedRun(runId);access.requireWrite(actor,run.orgId());access.requireVoter(actor,runId);if(!"PREVIEW".equals(run.status()))locked();if(!GRADES.contains(grade)||reason==null||reason.isBlank())invalid("BOUNDARY_VOTE_INVALID","边界等级与表决理由不能为空");Long exists=jdbc.sql("SELECT COUNT(*) FROM settlement_candidate WHERE run_id=:runId AND user_id=:userId AND manual_required=TRUE").param("runId",runId).param("userId",userId).query(Long.class).single();if(exists!=1)throw new ApiException("BOUNDARY_NOT_FOUND","该人员没有待表决同分边界",HttpStatus.NOT_FOUND);
        jdbc.sql("INSERT INTO settlement_boundary_vote(id,run_id,user_id,supervisor_id,grade,reason) VALUES (:id,:runId,:userId,:supervisorId,:grade,:reason) ON CONFLICT (run_id,user_id,supervisor_id) DO UPDATE SET grade=EXCLUDED.grade,reason=EXCLUDED.reason,updated_at=CURRENT_TIMESTAMP").param("id",UUID.randomUUID()).param("runId",runId).param("userId",userId).param("supervisorId",actor.userId()).param("grade",grade).param("reason",reason.trim()).update();
        GradeVote winner=jdbc.sql("SELECT v.grade,COUNT(*) votes FROM settlement_boundary_vote v JOIN settlement_approver a ON a.run_id=v.run_id AND a.user_id=v.supervisor_id WHERE v.run_id=:runId AND v.user_id=:userId GROUP BY v.grade ORDER BY votes DESC,v.grade LIMIT 1").param("runId",runId).param("userId",userId).query((rs,n)->new GradeVote(rs.getString("grade"),rs.getInt("votes"))).single();if(winner.votes()>=2)jdbc.sql("UPDATE settlement_candidate SET manual_grade=:grade,manual_reason=:reason,decided_by=:actorId,manual_required=FALSE WHERE run_id=:runId AND user_id=:userId").param("grade",winner.grade()).param("reason","已达到边界表决通过条件").param("actorId",actor.userId()).param("runId",runId).param("userId",userId).update();audit.record(actor.userId(),"SETTLEMENT_BOUNDARY_VOTE","SETTLEMENT_RUN",runId,"{\"grade\":\""+grade+"\"}",requestId);return buildView(runId);}

    @Transactional
    public SettlementView confirm(CurrentUser actor,UUID runId,String comment,String requestId){requireSupervisor(actor);RunRow run=lockedRun(runId);access.requireWrite(actor,run.orgId());access.requireVoter(actor,runId);if(!"PREVIEW".equals(run.status()))locked();long unresolved=jdbc.sql("SELECT COUNT(*) FROM settlement_candidate WHERE run_id=:id AND manual_required=TRUE").param("id",runId).query(Long.class).single();if(unresolved>0)throw new ApiException("BOUNDARY_CONFIRMATION_REQUIRED","仍有同分边界尚未达到当前表决条件",HttpStatus.CONFLICT);try{jdbc.sql("INSERT INTO settlement_confirmation(id,run_id,supervisor_id,comment) VALUES (:id,:runId,:supervisorId,:comment)").param("id",UUID.randomUUID()).param("runId",runId).param("supervisorId",actor.userId()).param("comment",clean(comment)).update();}catch(org.springframework.dao.DataIntegrityViolationException ex){throw new ApiException("SETTLEMENT_ALREADY_CONFIRMED","当前账号已完成本次确认",HttpStatus.CONFLICT);}audit.record(actor.userId(),"SETTLEMENT_CONFIRM","SETTLEMENT_RUN",runId,"{}",requestId);if(confirmationCount(runId)>=access.voters(runId).size()&&eligibleToLock(run.period()))publishInternal(run,actor.userId(),requestId);return buildView(runId);}

    @Transactional
    public SettlementView publish(CurrentUser actor,UUID runId,String requestId){requireSupervisor(actor);RunRow run=lockedRun(runId);access.requireWrite(actor,run.orgId());access.requireVoter(actor,runId);if(!"PREVIEW".equals(run.status()))locked();if(access.voters(runId).isEmpty()||confirmationCount(runId)<access.voters(runId).size())throw new ApiException("ALL_SUPERVISORS_REQUIRED","当前审批确认条件尚未满足，暂时无法封存",HttpStatus.CONFLICT);if(!eligibleToLock(run.period()))throw new ApiException("SETTLEMENT_TOO_EARLY","月度绩效只能在次月5日及以后封存",HttpStatus.CONFLICT);publishInternal(run,actor.userId(),requestId);return buildView(runId);}

    private void publishInternal(RunRow run,UUID actorId,String requestId){long unresolved=jdbc.sql("SELECT COUNT(*) FROM settlement_candidate WHERE run_id=:id AND manual_required=TRUE").param("id",run.id()).query(Long.class).single();if(unresolved>0)throw new ApiException("BOUNDARY_CONFIRMATION_REQUIRED","仍有同分边界未完成表决",HttpStatus.CONFLICT);List<Snapshot> rows=jdbc.sql("SELECT user_id,COALESCE(manual_grade,proposed_grade) grade,rank_no,total,base,bonus,penalty,shift_count,average_score FROM settlement_candidate WHERE run_id=:id").param("id",run.id()).query((rs,n)->new Snapshot(rs.getObject("user_id",UUID.class),rs.getString("grade"),rs.getInt("rank_no"),rs.getBigDecimal("total"),rs.getBigDecimal("base"),rs.getBigDecimal("bonus"),rs.getBigDecimal("penalty"),rs.getInt("shift_count"),rs.getBigDecimal("average_score"))).list();for(Snapshot row:rows)jdbc.sql("INSERT INTO grade_snapshot(id,period,user_id,grade,rank_no,settlement_version,status,settlement_run_id,total,base,bonus,penalty,shift_count,average_score,published_at) VALUES (:id,:period,:userId,:grade,:rank,:version,'PUBLISHED',:runId,:total,:base,:bonus,:penalty,:shiftCount,:average,CURRENT_TIMESTAMP)").param("id",UUID.randomUUID()).param("period",run.period()).param("userId",row.userId()).param("grade",row.grade()).param("rank",row.rank()).param("version",run.version()).param("runId",run.id()).param("total",row.total()).param("base",row.base()).param("bonus",row.bonus()).param("penalty",row.penalty()).param("shiftCount",row.shiftCount()).param("average",row.average()).update();jdbc.sql("UPDATE settlement_run SET status='PUBLISHED',published_by=:actorId,published_at=CURRENT_TIMESTAMP WHERE id=:id AND status='PREVIEW'").param("actorId",actorId).param("id",run.id()).update();audit.record(actorId,"SETTLEMENT_PUBLISH","SETTLEMENT_RUN",run.id(),"{\"status\":\"PUBLISHED\"}",requestId);jdbc.sql("SELECT user_id FROM settlement_candidate WHERE run_id=:id").param("id",run.id()).query(UUID.class).list().forEach(userId->notifications.create(userId,"SETTLEMENT_PUBLISHED","月度绩效已封存",run.period()+"月最终积分、排名和等级已经发布。","SETTLEMENT_RUN",run.id(),false));}

    @Transactional
    public void autoPrepare(){LocalDate today=LocalDate.now(ZONE);if(today.getDayOfMonth()<5)return;String period=YearMonth.from(today.minusMonths(1)).toString();UUID root=departmentId();Long published=jdbc.sql("SELECT COUNT(*) FROM grade_snapshot g JOIN settlement_run r ON r.id=g.settlement_run_id WHERE g.period=:period AND g.status='PUBLISHED' AND r.org_unit_id=:root").param("period",period).param("root",root).query(Long.class).single();if(published>0)return;Long run=jdbc.sql("SELECT COUNT(*) FROM settlement_run WHERE period=:period AND org_unit_id=:root AND status IN ('PREVIEW','PUBLISHED')").param("period",period).param("root",root).query(Long.class).single();if(run>0)return;CurrentUser actor=firstSupervisor(root);try{preview(actor,period,root,"AUTO-"+period,"auto-settlement-"+period);}catch(ApiException ex){if("PENDING_BUSINESS_EXISTS".equals(ex.code()))notifySupervisors(null,root,"月度封存已延后",ex.getMessage());else throw ex;}}

    private SettlementView buildView(UUID runId){RunRow run=run(runId);List<SettlementView.Candidate> candidates=jdbc.sql("SELECT c.user_id,u.display_name,u.employee_no,c.total,c.base,c.bonus,c.penalty,c.shift_count,c.average_score,c.proposed_grade,c.manual_grade,c.rank_no,c.manual_required FROM settlement_candidate c JOIN app_user u ON u.id=c.user_id WHERE c.run_id=:id ORDER BY c.rank_no").param("id",runId).query((rs,n)->new SettlementView.Candidate(rs.getObject("user_id",UUID.class),rs.getString("display_name"),rs.getString("employee_no"),rs.getBigDecimal("total"),rs.getBigDecimal("base"),rs.getBigDecimal("bonus"),rs.getBigDecimal("penalty"),rs.getInt("shift_count"),rs.getBigDecimal("average_score"),rs.getString("proposed_grade"),rs.getString("manual_grade")==null?rs.getString("proposed_grade"):rs.getString("manual_grade"),rs.getInt("rank_no"),rs.getBoolean("manual_required"))).list();return new SettlementView(run.id(),run.period(),run.version(),run.status(),candidates.stream().filter(SettlementView.Candidate::manualRequired).count(),confirmationCount(runId),(int)access.voters(runId).size(),candidates);}
    private List<ScoreData> scores(String period,UUID orgId){YearMonth month=YearMonth.parse(period);return jdbc.sql("WITH RECURSIVE tree AS (SELECT id FROM org_unit WHERE id=:orgId AND NOT is_review_data UNION SELECT o.id FROM org_unit o JOIN tree t ON o.parent_id=t.id WHERE NOT o.is_review_data) SELECT u.id,COALESCE(s.total,0) total,COALESCE(s.base,0) base,COALESCE(s.bonus,0) bonus,COALESCE(s.penalty,0) penalty,(SELECT COUNT(*) FROM shift_score sh WHERE sh.user_id=u.id AND sh.status='POSTED' AND sh.business_date>=:from AND sh.business_date<:to) shift_count FROM app_user u JOIN tree t ON t.id=u.org_unit_id LEFT JOIN score_summary s ON s.user_id=u.id AND s.period=:period WHERE u.status='ACTIVE' AND u.is_review_account=FALSE AND EXISTS(SELECT 1 FROM role_binding rb WHERE rb.user_id=u.id AND rb.role_code IN ('TECHNICIAN','ASSISTANT_ENGINEER'))").param("orgId",orgId).param("from",month.atDay(1)).param("to",month.plusMonths(1).atDay(1)).param("period",period).query((rs,n)->{int shifts=rs.getInt("shift_count");BigDecimal total=rs.getBigDecimal("total"),base=rs.getBigDecimal("base");return new ScoreData(rs.getObject("id",UUID.class),total,base,rs.getBigDecimal("bonus"),rs.getBigDecimal("penalty"),shifts,shifts==0?BigDecimal.ZERO:total.divide(BigDecimal.valueOf(shifts),6,RoundingMode.HALF_UP),shifts==0?BigDecimal.ZERO:base.divide(BigDecimal.valueOf(shifts*10L),6,RoundingMode.HALF_UP));}).list().stream().filter(item->item.shiftCount()>0).toList();}
    private GradeDistribution.ScoreInput rankInput(ScoreData item){return new GradeDistribution.ScoreInput(item.userId(),item.average(),item.baseRate(),item.bonus(),item.penalty());}
    long pendingCount(YearMonth month,UUID orgId){
        OffsetDateTime start=month.atDay(1).atStartOfDay(ZONE).toOffsetDateTime(),end=month.plusMonths(1).atDay(1).atStartOfDay(ZONE).toOffsetDateTime();
        return jdbc.sql("""
                WITH RECURSIVE tree AS (
                  SELECT id FROM org_unit WHERE id=:orgId AND NOT is_review_data
                  UNION SELECT o.id FROM org_unit o JOIN tree t ON o.parent_id=t.id WHERE NOT o.is_review_data
                ), people AS (SELECT id FROM app_user WHERE org_unit_id IN (SELECT id FROM tree) AND NOT is_review_account)
                SELECT
                  (SELECT COUNT(*) FROM performance_case p WHERE p.target_user_id IN (SELECT id FROM people)
                    AND p.occurred_at>=:start AND p.occurred_at<:end AND p.status IN ('PENDING_ASSISTANT','PENDING_SUPERVISOR','RETURNED')) +
                  (SELECT COUNT(*) FROM performance_appeal a JOIN performance_case p ON p.id=a.case_id
                    WHERE p.target_user_id IN (SELECT id FROM people) AND a.applicant_id IN (SELECT id FROM people)
                    AND p.occurred_at>=:start AND p.occurred_at<:end AND a.status='PENDING') +
                  (SELECT COUNT(*) FROM equipment_incident i JOIN app_user u ON u.id=i.created_by
                    JOIN production_line l ON l.id=i.line_id WHERE i.team_id IN (SELECT id FROM tree)
                    AND NOT u.is_review_account AND NOT l.is_review_data AND i.business_date>=:from AND i.business_date<:to AND i.status NOT IN ('ARCHIVED','VOID')) +
                  (SELECT COUNT(*) FROM d_grade_nomination n WHERE n.user_id IN (SELECT id FROM people) AND n.period=:period AND n.status='PENDING') +
                  (SELECT COUNT(*) FROM d_grade_appeal a JOIN d_grade_nomination n ON n.id=a.nomination_id
                    WHERE n.user_id IN (SELECT id FROM people) AND n.period=:period AND a.status='PENDING')
                """).param("orgId",orgId).param("start",start).param("end",end).param("from",month.atDay(1))
                .param("to",month.plusMonths(1).atDay(1)).param("period",month.toString()).query(Long.class).single();
    }
    private RunRow lockedRun(UUID id){jdbc.sql("SELECT id FROM settlement_run WHERE id=:id FOR UPDATE").param("id",id).query(UUID.class).optional().orElseThrow(()->new ApiException("SETTLEMENT_NOT_FOUND","结算批次不存在",HttpStatus.NOT_FOUND));return run(id);}
    private RunRow run(UUID id){return jdbc.sql("SELECT id,period,org_unit_id,settlement_version,status FROM settlement_run WHERE id=:id").param("id",id).query((rs,n)->new RunRow(rs.getObject("id",UUID.class),rs.getString("period"),rs.getObject("org_unit_id",UUID.class),rs.getString("settlement_version"),rs.getString("status"))).optional().orElseThrow(()->new ApiException("SETTLEMENT_NOT_FOUND","结算批次不存在",HttpStatus.NOT_FOUND));}
    private int confirmationCount(UUID runId){return jdbc.sql("SELECT COUNT(*) FROM settlement_confirmation c JOIN settlement_approver a ON a.run_id=c.run_id AND a.user_id=c.supervisor_id WHERE c.run_id=:id").param("id",runId).query(Long.class).single().intValue();}

    private UUID departmentId(){return jdbc.sql("SELECT id FROM org_unit WHERE type='DEPARTMENT' AND name='测试工程部' ORDER BY created_at LIMIT 1").query(UUID.class).optional().orElseThrow(()->new ApiException("DEPARTMENT_NOT_FOUND","未找到测试工程部组织",HttpStatus.CONFLICT));}
    private void requireDepartment(UUID id){Long count=jdbc.sql("SELECT COUNT(*) FROM org_unit WHERE id=:id AND type='DEPARTMENT' AND NOT is_review_data").param("id",id).query(Long.class).single();if(count!=1)invalid("INVALID_SETTLEMENT_ORG","仅可结算正式部门");}
    private CurrentUser firstSupervisor(UUID orgId){UUID id=access.supervisors(orgId).stream().findFirst().orElseThrow(()->new ApiException("SUPERVISOR_NOT_FOUND","没有有权准备本组织月度封存的主管",HttpStatus.CONFLICT));return jdbc.sql("SELECT id,employee_no,display_name,org_unit_id FROM app_user WHERE id=:id").param("id",id).query((rs,n)->new CurrentUser(rs.getObject("id",UUID.class),rs.getString("employee_no"),rs.getString("display_name"),rs.getObject("org_unit_id",UUID.class),Set.of(BusinessRoles.SUPERVISOR),false)).single();}
    private void notifySupervisors(UUID sourceId,UUID orgId,String title,String content){(sourceId==null?access.supervisors(orgId):access.voters(sourceId)).forEach(id->notifications.create(id,"SETTLEMENT_PENDING",title,content,"SETTLEMENT_RUN",sourceId,false));}
    private boolean eligibleToLock(String period){return !LocalDate.now(ZONE).isBefore(YearMonth.parse(period).plusMonths(1).atDay(5));}
    private void requireSupervisor(CurrentUser actor){if(!actor.roles().contains(BusinessRoles.SUPERVISOR))throw new ApiException("FORBIDDEN","仅主管可以生成、表决和确认月度绩效",HttpStatus.FORBIDDEN);}
    private void requireViewer(CurrentUser actor){if(!actor.roles().contains(BusinessRoles.SUPERVISOR)&&!actor.roles().contains(BusinessRoles.DEPARTMENT_MANAGER))throw new ApiException("FORBIDDEN","无权查看月度结算",HttpStatus.FORBIDDEN);}
    private void invalid(String code,String message){throw new ApiException(code,message,HttpStatus.BAD_REQUEST);}private void locked(){throw new ApiException("SETTLEMENT_LOCKED","结算已封存或状态不可操作",HttpStatus.CONFLICT);}private String clean(String value){return value==null||value.isBlank()?null:value.trim();}
    private record ScoreData(UUID userId,BigDecimal total,BigDecimal base,BigDecimal bonus,BigDecimal penalty,int shiftCount,BigDecimal average,BigDecimal baseRate){}
    private record RunRow(UUID id,String period,UUID orgId,String version,String status){}private record Snapshot(UUID userId,String grade,int rank,BigDecimal total,BigDecimal base,BigDecimal bonus,BigDecimal penalty,int shiftCount,BigDecimal average){}private record GradeVote(String grade,int votes){}
}
